// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Zk1-v-ZXx7Aurz5ySvQaJPuy9re7gE0',
    appId: '1:808781657520:web:c63e6de723a88e27485275',
    messagingSenderId: '808781657520',
    projectId: 'sh-fcm-demo',
    authDomain: 'sh-fcm-demo.firebaseapp.com',
    storageBucket: 'sh-fcm-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvAZWRCIfqB82HO0y0Dvb3mzPXWigOgBY',
    appId: '1:808781657520:android:f9b84993da89d904485275',
    messagingSenderId: '808781657520',
    projectId: 'sh-fcm-demo',
    storageBucket: 'sh-fcm-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMKbtE6osA_lYlvQ5Lsp_KrzK5Rcc-IF8',
    appId: '1:808781657520:ios:8f463ca15dcd5a5a485275',
    messagingSenderId: '808781657520',
    projectId: 'sh-fcm-demo',
    storageBucket: 'sh-fcm-demo.appspot.com',
    iosClientId: '808781657520-866uh287tvegbi5p6365l7snk6o3qsbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMKbtE6osA_lYlvQ5Lsp_KrzK5Rcc-IF8',
    appId: '1:808781657520:ios:8f463ca15dcd5a5a485275',
    messagingSenderId: '808781657520',
    projectId: 'sh-fcm-demo',
    storageBucket: 'sh-fcm-demo.appspot.com',
    iosClientId: '808781657520-866uh287tvegbi5p6365l7snk6o3qsbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
